// 일본어 단어 데이터 (jp, romaji, meaning_ko)
// CSV로 확장하려면 같은 형식의 배열로 data.js를 교체하면 됩니다.
window.VOCAB_DATA = [
  { jp: "水", romaji: "mizu", meaning_ko: "물" },
  { jp: "火", romaji: "hi", meaning_ko: "불" },
  { jp: "人", romaji: "hito", meaning_ko: "사람" },
  { jp: "日", romaji: "hi", meaning_ko: "날, 해" },
  { jp: "本", romaji: "hon", meaning_ko: "책" },
  { jp: "日本", romaji: "nihon", meaning_ko: "일본" },
  { jp: "食べる", romaji: "taberu", meaning_ko: "먹다" },
  { jp: "飲む", romaji: "nomu", meaning_ko: "마시다" },
  { jp: "見る", romaji: "miru", meaning_ko: "보다" },
  { jp: "聞く", romaji: "kiku", meaning_ko: "듣다" },
  { jp: "行く", romaji: "iku", meaning_ko: "가다" },
  { jp: "来る", romaji: "kuru", meaning_ko: "오다" },
  { jp: "大きい", romaji: "ookii", meaning_ko: "크다" },
  { jp: "小さい", romaji: "chiisai", meaning_ko: "작다" },
  { jp: "新しい", romaji: "atarashii", meaning_ko: "새롭다" },
  { jp: "古い", romaji: "furui", meaning_ko: "오래되다" },
  { jp: "暑い", romaji: "atsui", meaning_ko: "덥다" },
  { jp: "寒い", romaji: "samui", meaning_ko: "춥다" },
  { jp: "高い", romaji: "takai", meaning_ko: "높다, 비싸다" },
  { jp: "安い", romaji: "yasui", meaning_ko: "싸다" },
  { jp: "いい", romaji: "ii", meaning_ko: "좋다" },
  { jp: "悪い", romaji: "warui", meaning_ko: "나쁘다" },
  { jp: "難しい", romaji: "muzukashii", meaning_ko: "어렵다" },
  { jp: "易しい", romaji: "yasashii", meaning_ko: "쉽다" },
  { jp: "速い", romaji: "hayai", meaning_ko: "빠르다" },
  { jp: "遅い", romaji: "osoi", meaning_ko: "느리다" },
  { jp: "朝", romaji: "asa", meaning_ko: "아침" },
  { jp: "昼", romaji: "hiru", meaning_ko: "낮" },
  { jp: "夜", romaji: "yoru", meaning_ko: "밤" },
  { jp: "今日", romaji: "kyou", meaning_ko: "오늘" },
  { jp: "明日", romaji: "ashita", meaning_ko: "내일" },
  { jp: "昨日", romaji: "kinou", meaning_ko: "어제" },
  { jp: "今", romaji: "ima", meaning_ko: "지금" },
  { jp: "時", romaji: "toki", meaning_ko: "때, 시간" },
  { jp: "年", romaji: "toshi", meaning_ko: "해, 나이" },
  { jp: "月", romaji: "tsuki", meaning_ko: "달, 월" },
  { jp: "名前", romaji: "namae", meaning_ko: "이름" },
  { jp: "友達", romaji: "tomodachi", meaning_ko: "친구" },
  { jp: "家族", romaji: "kazoku", meaning_ko: "가족" },
  { jp: "学校", romaji: "gakkou", meaning_ko: "학교" },
  { jp: "会社", romaji: "kaisha", meaning_ko: "회사" },
  { jp: "家", romaji: "ie", meaning_ko: "집" },
  { jp: "部屋", romaji: "heya", meaning_ko: "방" },
  { jp: "車", romaji: "kuruma", meaning_ko: "자동차" },
  { jp: "電車", romaji: "densha", meaning_ko: "전철" },
  { jp: "駅", romaji: "eki", meaning_ko: "역" },
  { jp: "空港", romaji: "kuukou", meaning_ko: "공항" },
  { jp: "お金", romaji: "okane", meaning_ko: "돈" },
  { jp: "時間", romaji: "jikan", meaning_ko: "시간" },
  { jp: "電話", romaji: "denwa", meaning_ko: "전화" },
  { jp: "手", romaji: "te", meaning_ko: "손" },
  { jp: "目", romaji: "me", meaning_ko: "눈" },
  { jp: "口", romaji: "kuchi", meaning_ko: "입" },
  { jp: "耳", romaji: "mimi", meaning_ko: "귀" },
  { jp: "頭", romaji: "atama", meaning_ko: "머리" },
  { jp: "心", romaji: "kokoro", meaning_ko: "마음" },
  { jp: "元気", romaji: "genki", meaning_ko: "건강, 기운" },
  { jp: "元気です", romaji: "genki desu", meaning_ko: "잘 지냅니다" },
  { jp: "好き", romaji: "suki", meaning_ko: "좋아함" },
  { jp: "嫌い", romaji: "kirai", meaning_ko: "싫어함" },
  { jp: "勉強", romaji: "benkyou", meaning_ko: "공부" },
  { jp: "仕事", romaji: "shigoto", meaning_ko: "일" },
  { jp: "休み", romaji: "yasumi", meaning_ko: "휴식, 휴일" },
  { jp: "旅行", romaji: "ryokou", meaning_ko: "여행" },
  { jp: "映画", romaji: "eiga", meaning_ko: "영화" },
  { jp: "音楽", romaji: "ongaku", meaning_ko: "음악" },
  { jp: "料理", romaji: "ryouri", meaning_ko: "요리" },
  { jp: "魚", romaji: "sakana", meaning_ko: "생선" },
  { jp: "肉", romaji: "niku", meaning_ko: "고기" },
  { jp: "野菜", romaji: "yasai", meaning_ko: "채소" },
  { jp: "果物", romaji: "kudamono", meaning_ko: "과일" },
  { jp: "牛乳", romaji: "gyuunyuu", meaning_ko: "우유" },
  { jp: "コーヒー", romaji: "koohii", meaning_ko: "커피" },
  { jp: "紅茶", romaji: "koucha", meaning_ko: "홍차" },
  { jp: "ありがとう", romaji: "arigatou", meaning_ko: "감사합니다" },
  { jp: "すみません", romaji: "sumimasen", meaning_ko: "죄송합니다" },
  { jp: "おはよう", romaji: "ohayou", meaning_ko: "안녕 (아침)" },
  { jp: "こんにちは", romaji: "konnichiwa", meaning_ko: "안녕하세요" },
  { jp: "こんばんは", romaji: "konbanwa", meaning_ko: "안녕하세요 (저녁)" },
  { jp: "さようなら", romaji: "sayounara", meaning_ko: "안녕히 가세요" },
  { jp: "はい", romaji: "hai", meaning_ko: "네" },
  { jp: "いいえ", romaji: "iie", meaning_ko: "아니요" },
  { jp: "分かる", romaji: "wakaru", meaning_ko: "이해하다" },
  { jp: "知る", romaji: "shiru", meaning_ko: "알다" },
  { jp: "思う", romaji: "omou", meaning_ko: "생각하다" },
  { jp: "言う", romaji: "iu", meaning_ko: "말하다" },
  { jp: "書く", romaji: "kaku", meaning_ko: "쓰다" },
  { jp: "読む", romaji: "yomu", meaning_ko: "읽다" },
  { jp: "買う", romaji: "kau", meaning_ko: "사다" },
  { jp: "売る", romaji: "uru", meaning_ko: "팔다" },
  { jp: "作る", romaji: "tsukuru", meaning_ko: "만들다" },
  { jp: "起きる", romaji: "okiru", meaning_ko: "일어나다" },
  { jp: "寝る", romaji: "neru", meaning_ko: "자다" },
  { jp: "開ける", romaji: "akeru", meaning_ko: "열다" },
  { jp: "閉める", romaji: "shimeru", meaning_ko: "닫다" },
  { jp: "始まる", romaji: "hajimaru", meaning_ko: "시작되다" },
  { jp: "終わる", romaji: "owaru", meaning_ko: "끝나다" },
  { jp: "北", romaji: "kita", meaning_ko: "북쪽" },
  { jp: "南", romaji: "minami", meaning_ko: "남쪽" },
  { jp: "東", romaji: "higashi", meaning_ko: "동쪽" },
  { jp: "西", romaji: "nishi", meaning_ko: "서쪽" },
  { jp: "右", romaji: "migi", meaning_ko: "오른쪽" },
  { jp: "左", romaji: "hidari", meaning_ko: "왼쪽" },
  { jp: "上", romaji: "ue", meaning_ko: "위" },
  { jp: "下", romaji: "shita", meaning_ko: "아래" },
  { jp: "中", romaji: "naka", meaning_ko: "안" },
  { jp: "外", romaji: "soto", meaning_ko: "밖" },
  { jp: "前", romaji: "mae", meaning_ko: "앞" },
  { jp: "後", romaji: "ushiro", meaning_ko: "뒤" },
  { jp: "近い", romaji: "chikai", meaning_ko: "가깝다" },
  { jp: "遠い", romaji: "tooi", meaning_ko: "멀다" },
  { jp: "多い", romaji: "ooi", meaning_ko: "많다" },
  { jp: "少ない", romaji: "sukunai", meaning_ko: "적다" },
  { jp: "赤", romaji: "aka", meaning_ko: "빨강" },
  { jp: "青", romaji: "ao", meaning_ko: "파랑" },
  { jp: "白", romaji: "shiro", meaning_ko: "흰색" },
  { jp: "黒", romaji: "kuro", meaning_ko: "검정" },
  { jp: "緑", romaji: "midori", meaning_ko: "초록" }
];
